import type { Metadata } from "next";
import "../globals.css";
import { kanit } from "../font";
import AppHeader from "@/components/app/AppHeader";

export const metadata: Metadata = {
  title: "E-commerce Platform",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kanit.className}`}>
        <AppHeader />
        {children}
      </body>
    </html>
  );
}
